Created drop and minor updates

diff --git a/backend-flask/bin/ddb/drop b/backend-flask/bin/ddb/drop
--- a/backend-flask/bin/ddb/drop
+++ b/backend-flask/bin/ddb/drop
@@ -1,1 +1,22 @@
 #! /usr/bin/bash
+
+set -e # stop if it fails at any point
+
+#./bin/ddb/drop cruddur-messages prod
+
+if [ -z "$1" ]; then
+    echo "Not table_Name argument supplied eg"
+    exit 1
+fi
+Table_NAME=$1
+
+if [ "$2" = "prod" ]; then
+    ENDPOINT_URL=""
+else
+    ENDPOINT_URL="--endpoint-url=http://localhost:8000"
+fi
+
+echo "deleting table: $TABLE_NAME"
+
+aws dynamodb delete-table $ENDPOINT_URL \
+--table-name $Table_NAME
